force-app/main/default/objects/Maintenance_Part__c/Maintenance_Part__c.object-meta.xml
<CustomObject>
    <label>Maintenance Part</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Maintenance Part Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Part__c/fields/Maintenance_Request__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Request__c</fullName>
    <label>Maintenance Request</label>
    <referenceTo>Maintenance_Request__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Part_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Part_Inventory__c</fullName>
    <label>Part Inventory</label>
    <referenceTo>Part_Inventory__c</referenceTo>
    <relationshipLabel>Maintenance Parts</relationshipLabel>
    <relationshipName>Maintenance_Parts</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintenance_Part__c/fields/Quantity_Utilized__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Utilized__c</fullName>
    <label>Quantity Utilized</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <label>Maintenance Request</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Maintenance Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Date__c</fullName>
    <label>Maintenance Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Odometer_Reading__c</fullName>
    <label>Odometer Reading</label>
    <precision>18</precision>
    <required>true</required>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not confirmed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <label>Vehicle</label>
    <referenceTo>Vehicle__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/Part_Inventory__c.object-meta.xml
<CustomObject>
    <label>Part Inventory</label>
    <nameField>
        <label>Part Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Inventory__c/fields/Parent_Part__c.field-meta.xml
<CustomField>
    <fullName>Parent_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Part</label>
    <referenceTo>Part_Inventory__c</referenceTo>
    <relationshipLabel>Part Inventories</relationshipLabel>
    <relationshipName>Part_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Part_Inventory__c/fields/Quantity_in_Stock__c.field-meta.xml
<CustomField>
    <fullName>Quantity_in_Stock__c</fullName>
    <label>Quantity in Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Last_Known_Odometer_Reading__c.field-meta.xml
<CustomField>
    <fullName>Last_Known_Odometer_Reading__c</fullName>
    <label>Last Known Odometer Reading</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MaintenancePartTriggerTest.cls
@isTest
public class MaintenancePartTriggerTest {
	@isTest
    Public static void Test1(){
        Account a = new account(name = 'test');
        insert a;
        contact c = new contact(lastName = 'contact',accountId = a.id);
        insert c;
        Vehicle__c  v = new Vehicle__c (Make__c = 'Ford',
                                        Model__c = 'Fiesta', 
                                        year__c = 2020, 
                                        Color__c = 'Blue', 
                                        Contact__c = c.id,
                                        Last_Known_Odometer_Reading__c = 1000,
                                        Last_Service_Date__c =  date.today().adddays(-100));
        insert v;
        Maintenance_Request__c MR = new Maintenance_Request__c (Maintenance_Date__c = date.today(),
                                                               Odometer_Reading__c = 1200,status__c = 'Not Confirmed',
                                                               Vehicle__c = v.id);
        Insert MR;
        Part_Inventory__c Mainpart = new Part_Inventory__c (Name = 'main',
                                                           Part_Number__c = 1,
                                                           Quantity_in_Stock__c = 5);
        insert MainPart;
        Part_Inventory__c subpart1 = new Part_Inventory__c (Name = 'subpart1',
                                                           Part_Number__c = 2,
                                                           Quantity_in_Stock__c = 7,
                                                           Parent_Part__c = MainPart.id);
        insert subpart1;
        Part_Inventory__c subpart2 = new Part_Inventory__c (Name = 'subpart2',
                                                           Part_Number__c = 3,
                                                           Quantity_in_Stock__c = 8,
                                                            Parent_Part__c = MainPart.id);
        insert subpart2;
        
        Maintenance_Part__c MP = new Maintenance_Part__c(Maintenance_Request__c = MR.id,
                                                        Part_Inventory__c = Mainpart.Id,
                                                        Quantity_Utilized__c = 7);
        insert MP;
        MP.Quantity_Utilized__c = 2;
        update MP;
        
        MP.Quantity_Utilized__c = 1;
        update MP;
        
        MP.Quantity_Utilized__c = 12;
        update MP;
        
        delete MP;
        
        Mainpart.Quantity_in_Stock__c = 15;
        update Mainpart;
        
    }
}